In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("train.csv")

In [ ]:
data.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [ ]:
test = pd.read_csv("test.csv")

In [ ]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [ ]:
p = data.fillna("AA")

In [ ]:
q = test.fillna("AA")

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
orcode = OrdinalEncoder()

In [ ]:
train = orcode.fit_transform(p[["MSZoning" , "Street" ,"Alley" , "LotShape" , "LandContour" ,"Utilities","LotConfig","LandSlope"  , "Neighborhood" , "Condition1" , "Condition2" , "BldgType" , "HouseStyle" , "RoofStyle" , "RoofMatl" , "Exterior1st" , "Exterior2nd" , "MasVnrType" , "ExterQual" , "ExterCond" , "Foundation" , "BsmtQual" , "BsmtCond" , "BsmtExposure" , "BsmtFinType1" , "BsmtFinType2" , "Heating" , "HeatingQC" , "CentralAir" , "Electrical" , "KitchenQual" , "Functional" , "FireplaceQu" , "GarageType" , "GarageFinish" , "GarageQual" , "GarageCond" , "PavedDrive" , "PoolQC" , "Fence" , "MiscFeature" , "SaleType" , "SaleCondition"]])[:1460]

In [ ]:
t = pd.DataFrame(train , columns = ["MSZoning" , "Street" ,"Alley" , "LotShape" , "LandContour" ,"Utilities","LotConfig","LandSlope"  , "Neighborhood" , "Condition1" , "Condition2" , "BldgType" , "HouseStyle" , "RoofStyle" , "RoofMatl" , "Exterior1st" , "Exterior2nd" , "MasVnrType" , "ExterQual" , "ExterCond" , "Foundation" , "BsmtQual" , "BsmtCond" , "BsmtExposure" , "BsmtFinType1" , "BsmtFinType2" , "Heating" , "HeatingQC" , "CentralAir" , "Electrical" , "KitchenQual" , "Functional" , "FireplaceQu" , "GarageType" , "GarageFinish" , "GarageQual" , "GarageCond" , "PavedDrive" , "PoolQC" , "Fence" , "MiscFeature" , "SaleType" , "SaleCondition"])

In [ ]:
t

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,5.0,2.0,...,2.0,2.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
1,3.0,1.0,0.0,3.0,3.0,0.0,2.0,0.0,24.0,1.0,...,2.0,2.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
2,3.0,1.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,2.0,...,2.0,2.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
3,3.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,6.0,2.0,...,6.0,3.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,0.0
4,3.0,1.0,0.0,0.0,3.0,0.0,2.0,0.0,15.0,2.0,...,2.0,2.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,8.0,2.0,...,2.0,2.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
1456,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,14.0,2.0,...,2.0,3.0,5.0,5.0,2.0,0.0,3.0,0.0,8.0,4.0
1457,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,6.0,2.0,...,2.0,2.0,5.0,5.0,2.0,0.0,1.0,3.0,8.0,4.0
1458,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,12.0,2.0,...,2.0,3.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0
1459,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,7.0,2.0,...,2.0,1.0,5.0,5.0,2.0,0.0,0.0,0.0,8.0,4.0

In [ ]:
t["Id"] = data['Id']
t["MSSubClass"] = data['MSSubClass']
t["LotFrontage"] = data['LotFrontage']
t["LotArea"] = data['LotArea']
t["OverallQual"] = data['OverallQual']
t["OverallCond"] = data['OverallCond']
t["YearBuilt"] = data['YearBuilt']
t["YearRemodAdd"] = data['YearRemodAdd']
t["MasVnrArea"] = data['MasVnrArea']
t["BsmtFinSF1"] = data['BsmtFinSF1']
t["BsmtUnfSF"] = data['BsmtUnfSF']
t["TotalBsmtSF"] = data['TotalBsmtSF']
t["1stFlrSF"] = data['1stFlrSF']
t["2ndFlrSF"] = data['2ndFlrSF']
t["LowQualFinSF"] = data['LowQualFinSF']
t["GrLivArea"] = data['GrLivArea']
t["BsmtFullBath"] = data['BsmtFullBath']
t["BsmtHalfBath"] = data['BsmtHalfBath']
t["FullBath"] = data['FullBath']
t["HalfBath"] = data['HalfBath']
t["BedroomAbvGr"] = data['BedroomAbvGr']
t["KitchenAbvGr"] = data['KitchenAbvGr']
t["TotRmsAbvGrd"] = data['TotRmsAbvGrd']
t["Fireplaces"] = data['Fireplaces']
t["GarageCars"] = data['GarageCars']
t["GarageArea"] = data['GarageArea']
t["WoodDeckSF"] = data['WoodDeckSF']
t["OpenPorchSF"] = data['OpenPorchSF']
t["EnclosedPorch"] = data['EnclosedPorch']
t["3SsnPorch"] = data['3SsnPorch']
t["ScreenPorch"] = data['ScreenPorch']
t["PoolArea"] = data['PoolArea']
t["MiscVal"] = data['MiscVal']
t["MoSold"] = data['MoSold']
t["YrSold"] = data['YrSold']

In [ ]:
t.head(15)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,5.0,2.0,...,548,0,61,0,0,0,0,0,2,2008
1,3.0,1.0,0.0,3.0,3.0,0.0,2.0,0.0,24.0,1.0,...,460,298,0,0,0,0,0,0,5,2007
2,3.0,1.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,2.0,...,608,0,42,0,0,0,0,0,9,2008
3,3.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,6.0,2.0,...,642,0,35,272,0,0,0,0,2,2006
4,3.0,1.0,0.0,0.0,3.0,0.0,2.0,0.0,15.0,2.0,...,836,192,84,0,0,0,0,0,12,2008
5,3.0,1.0,0.0,0.0,3.0,0.0,4.0,0.0,11.0,2.0,...,480,40,30,0,320,0,0,700,10,2009
6,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,21.0,2.0,...,636,255,57,0,0,0,0,0,8,2007
7,3.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,14.0,4.0,...,484,235,204,228,0,0,0,350,11,2009
8,4.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,17.0,0.0,...,468,90,0,205,0,0,0,0,4,2008
9,3.0,1.0,0.0,3.0,3.0,0.0,0.0,0.0,3.0,0.0,...,205,0,4,0,0,0,0,0,1,2008
10,3.0,1.0,0.0,3.0,3.0,0.0,4.0,0.0,19.0,2.0,...,384,0,0,0,0,0,0,0,2,2008
11,3.0,1.0,0.0,0.0,3.0,0.0,4.0,0.0,16.0,2.0,...,736,147,21,0,0,0,0,0,7,2006
12,3.0,1.0,0.0,1.0,3.0,0.0,4.0,0.0,19.0,2.0,...,352,140,0,0,0,176,0,0,9,2008
13,3.0,1.0,0.0,0.0,3.0,0.0,4.0,0.0,5.0,2.0,...,840,160,33,0,0,0,0,0,8,2007
14,3.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,12.0,2.0,...,352,0,213,176,0,0,0,0,5,2008

In [ ]:
test_oe = orcode.fit_transform(q[["MSZoning" , "Street" ,"Alley" , "LotShape" , "LandContour" ,"Utilities","LotConfig","LandSlope"  , "Neighborhood" , "Condition1" , "Condition2" , "BldgType" , "HouseStyle" , "RoofStyle" , "RoofMatl" , "Exterior1st" , "Exterior2nd" , "MasVnrType" , "ExterQual" , "ExterCond" , "Foundation" , "BsmtQual" , "BsmtCond" , "BsmtExposure" , "BsmtFinType1" , "BsmtFinType2" , "Heating" , "HeatingQC" , "CentralAir" , "Electrical" , "KitchenQual" , "Functional" , "FireplaceQu" , "GarageType" , "GarageFinish" , "GarageQual" , "GarageCond" , "PavedDrive" , "PoolQC" , "Fence" , "MiscFeature" , "SaleType" , "SaleCondition"]])[:1460]

In [ ]:
te = pd.DataFrame(test_oe , columns = ["MSZoning" , "Street" ,"Alley" , "LotShape" , "LandContour" ,"Utilities","LotConfig","LandSlope"  , "Neighborhood" , "Condition1" , "Condition2" , "BldgType" , "HouseStyle" , "RoofStyle" , "RoofMatl" , "Exterior1st" , "Exterior2nd" , "MasVnrType" , "ExterQual" , "ExterCond" , "Foundation" , "BsmtQual" , "BsmtCond" , "BsmtExposure" , "BsmtFinType1" , "BsmtFinType2" , "Heating" , "HeatingQC" , "CentralAir" , "Electrical" , "KitchenQual" , "Functional" , "FireplaceQu" , "GarageType" , "GarageFinish" , "GarageQual" , "GarageCond" , "PavedDrive" , "PoolQC" , "Fence" , "MiscFeature" , "SaleType" , "SaleCondition"])

In [ ]:
te

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,3.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,12.0,1.0,...,2.0,3.0,4.0,5.0,2.0,0.0,3.0,0.0,9.0,4.0
1,4.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,12.0,2.0,...,2.0,3.0,4.0,5.0,2.0,0.0,0.0,1.0,9.0,4.0
2,4.0,1.0,0.0,0.0,3.0,1.0,4.0,0.0,8.0,2.0,...,2.0,1.0,4.0,5.0,2.0,0.0,3.0,0.0,9.0,4.0
3,4.0,1.0,0.0,0.0,3.0,1.0,4.0,0.0,8.0,2.0,...,2.0,1.0,4.0,5.0,2.0,0.0,0.0,0.0,9.0,4.0
4,4.0,1.0,0.0,0.0,1.0,1.0,4.0,0.0,22.0,2.0,...,2.0,2.0,4.0,5.0,2.0,0.0,0.0,0.0,9.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,5.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,10.0,2.0,...,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,9.0,4.0
1455,5.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,10.0,2.0,...,5.0,3.0,4.0,5.0,2.0,0.0,0.0,0.0,9.0,0.0
1456,4.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,11.0,2.0,...,6.0,3.0,4.0,5.0,2.0,0.0,0.0,0.0,9.0,0.0
1457,4.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,11.0,2.0,...,1.0,0.0,0.0,0.0,2.0,0.0,3.0,3.0,9.0,4.0
1458,4.0,1.0,0.0,3.0,3.0,1.0,4.0,1.0,11.0,2.0,...,2.0,1.0,4.0,5.0,2.0,0.0,0.0,0.0,9.0,4.0

In [ ]:
te["Id"] = test['Id']
te["MSSubClass"] = test['MSSubClass']
te["LotFrontage"] = test['LotFrontage']
te["LotArea"] = test['LotArea']
te["OverallQual"] = test['OverallQual']
te["OverallCond"] = test['OverallCond']
te["YearBuilt"] = test['YearBuilt']
te["YearRemodAdd"] = test['YearRemodAdd']
te["MasVnrArea"] = test['MasVnrArea']
te["BsmtFinSF1"] = test['BsmtFinSF1']
te["BsmtUnfSF"] = test['BsmtUnfSF']
te["TotalBsmtSF"] = test['TotalBsmtSF']
te["1stFlrSF"] = test['1stFlrSF']
te["2ndFlrSF"] = test['2ndFlrSF']
te["LowQualFinSF"] = test['LowQualFinSF']
te["GrLivArea"] = test['GrLivArea']
te["BsmtFullBath"] = test['BsmtFullBath']
te["BsmtHalfBath"] = test['BsmtHalfBath']
te["FullBath"] = test['FullBath']
te["HalfBath"] = test['HalfBath']
te["BedroomAbvGr"] = test['BedroomAbvGr']
te["KitchenAbvGr"] = test['KitchenAbvGr']
te["TotRmsAbvGrd"] = test['TotRmsAbvGrd']
te["Fireplaces"] = test['Fireplaces']
te["GarageCars"] = test['GarageCars']
te["GarageArea"] = test['GarageArea']
te["WoodDeckSF"] = test['WoodDeckSF']
te["OpenPorchSF"] = test['OpenPorchSF']
te["EnclosedPorch"] = test['EnclosedPorch']
te["3SsnPorch"] = test['3SsnPorch']
te["ScreenPorch"] = test['ScreenPorch']
te["PoolArea"] = test['PoolArea']
te["MiscVal"] = test['MiscVal']
te["MoSold"] = test['MoSold']
te["YrSold"] = test['YrSold']

In [ ]:
te

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,3.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,12.0,1.0,...,730.0,140,0,0,0,120,0,0,6,2010
1,4.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,12.0,2.0,...,312.0,393,36,0,0,0,0,12500,6,2010
2,4.0,1.0,0.0,0.0,3.0,1.0,4.0,0.0,8.0,2.0,...,482.0,212,34,0,0,0,0,0,3,2010
3,4.0,1.0,0.0,0.0,3.0,1.0,4.0,0.0,8.0,2.0,...,470.0,360,36,0,0,0,0,0,6,2010
4,4.0,1.0,0.0,0.0,1.0,1.0,4.0,0.0,22.0,2.0,...,506.0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,5.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,10.0,2.0,...,0.0,0,0,0,0,0,0,0,6,2006
1455,5.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,10.0,2.0,...,286.0,0,24,0,0,0,0,0,4,2006
1456,4.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,11.0,2.0,...,576.0,474,0,0,0,0,0,0,9,2006
1457,4.0,1.0,0.0,3.0,3.0,1.0,4.0,0.0,11.0,2.0,...,0.0,80,32,0,0,0,0,700,7,2006
1458,4.0,1.0,0.0,3.0,3.0,1.0,4.0,1.0,11.0,2.0,...,650.0,190,48,0,0,0,0,0,11,2006

In [ ]:
y = data["SalePrice"]

In [ ]:
t.isnull().any()

MSZoning       False
Street         False
Alley          False
LotShape       False
LandContour    False
               ...
ScreenPorch    False
PoolArea       False
MiscVal        False
MoSold         False
YrSold         False
Length: 78, dtype: bool

In [ ]:
te.isnull().any()

MSZoning       False
Street         False
Alley          False
LotShape       False
LandContour    False
               ...
ScreenPorch    False
PoolArea       False
MiscVal        False
MoSold         False
YrSold         False
Length: 78, dtype: bool

In [ ]:
te = te.fillna(0)

In [ ]:
t = t.fillna(0)

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
from sklearn import linear_model
cl = linear_model.Lasso(alpha=0.1)
cl.fit(t,y)
y_ = cl.predict(te)

In [ ]:
y_.size

1459

In [ ]:
d = pd.DataFrame(y_)
d.to_csv("p2.csv")

In [ ]:
clf = Ridge(alpha=1.0)

In [ ]:
clf.fit(t,y)

Ridge()

In [ ]:
y_predict  = clf.predict(te)

In [ ]:
y_predict.size

1459

In [ ]:
df = pd.DataFrame(y_predict)

In [ ]:
df

                  0
0      83783.772072
1     133511.308066
2     141617.669876
3     161183.724112
4     160507.075659
...             ...
1454   49728.716626
1455   27897.247643
1456  127812.053608
1457   92151.478512
1458  214511.824332

[1459 rows x 1 columns]

In [ ]:
df.to_csv("predicted.csv")